spring.application.name=system_management
server.port=8080
spring.threads.virtual.enabled=true

jwt.public.key=classpath:key/app.pub
jwt.private.key=classpath:key/app.key

spring.profiles.active=test

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000