# Este docker-compose é utilizado para criar o ambiente de desenvolvimento do software
# Sendo possivel, testar ferramentas externas no ambiente de desenvolvimento

services:
  spring_api:
    container_name: spring_api
    mem_limit: 1g
    cpus: 1
    build:
      context: ./../SpringApplication
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    env_file:
        - .env
    environment:
        SPRING_SERVER_PORT: ${SPRING_SERVER_PORT}
        SPRING_PROFILE: ${SPRING_PROFILE}
        REDIS_HOST: ${REDIS_HOST}
        EMAIL_HOST: ${EMAIL_HOST}
        EMAIL_PORT: ${EMAIL_PORT}
        EMAIL_USERNAME: ${EMAIL_USERNAME}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        EMAIL_SMTP_AUTH: ${EMAIL_SMTP_AUTH}
        EMAIL_SMTP_STARTTLS: ${EMAIL_SMTP_STARTTLS}
        EMAIL_HOST_TEST: ${EMAIL_HOST_TEST}
        EMAIL_PORT_TEST: ${EMAIL_PORT_TEST}
        EMAIL_USERNAME_TEST: ${EMAIL_USERNAME_TEST} 
        EMAIL_PASSWORD_TEST: ${EMAIL_PASSWORD_TEST}
        EMAIL_SMTP_AUTH_TEST: ${EMAIL_SMTP_AUTH_TEST}
        EMAIL_SMTP_STARTTLS_TEST: ${EMAIL_SMTP_STARTTLS_TEST}
        DATABASE_URL_TEST: ${DATABASE_URL_TEST}
        DATABASE_USERNAME_TEST: ${DATABASE_USERNAME_TEST}
        DATABASE_PASSWORD_TEST: ${DATABASE_PASSWORD_TEST}
        FRONT_END_URL: ${FRONT_END_URL}
        BACK_END_URL: ${BACK_END_URL}
        TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
        TURNSTILE_SECRET_KEY_TEST: ${TURNSTILE_SECRET_KEY_TEST}
        TURNSTILE_VERIFY_URL: ${TURNSTILE_VERIFY_URL}
        MERCADO_PAGO_ACCESS_TOKEN_TEST: ${MERCADO_PAGO_ACCESS_TOKEN_TEST}
        MERCADO_PAGO_NOTIFICATION_TEST: ${MERCADO_PAGO_NOTIFICATION_TEST}
        MERCADO_PAGO_WEBHOOK_SECRET_TEST: ${MERCADO_PAGO_WEBHOOK_SECRET_TEST}
    depends_on:
        postgres:
          condition: service_healthy
        redis:
            condition: service_started
        mailhog:
          condition: service_started
        minio:
          condition: service_started
    networks:
        - app_net
    restart: unless-stopped

  postgres:
    container_name: system_management_postgres_test
    image: postgres:15.14-alpine3.21
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1
    shm_size: 64mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-123
      POSTGRES_DB: system_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d system_management"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net

  redis:
    container_name: redis-local
    image: redis:7-alpine
    command: redis-server --appendonly yes
    mem_limit: 256m
    cpus: 0.3
    ports:
      - "6379:6379"
    networks:
      - app_net

  # Container para teste de servidor de email
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    mem_limit: 128m
    cpus: 0.2
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface web
    networks:
      - app_net

  # Container para teste de servidor de arquivo S3
  minio:
    container_name: minio-S3
    image: minio/minio
    mem_limit: 512m
    cpus: 0.5
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Interface web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_net

  # Container para teste de servidor proxy
  ngrok:
    container_name: ngrok_proxy
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: start --all --config /etc/ngrok/ngrok.yml
    mem_limit: 128mb
    cpus: 0.3
    environment:
    - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} 
    volumes:
      - ./ngrok.yml:/etc/ngrok/ngrok.yml
    ports:
      - "4040:4040" # painel web do ngrok
    networks:
      - app_net
    depends_on:
      - spring_api

volumes:
  postgres_test_data:
  minio_data:

networks:
  app_net:
    driver: bridge