# Este docker-compose é utilizado para criar o ambiente de desenvolvimento do software
# Sendo possivel, testar ferramentas externas no ambiente de desenvolvimento

services:
  postgres:
    container_name: system_management_postgres_test
    image: postgres:15.14-alpine3.21
    restart: unless-stopped
    shm_size: 64mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-123
      POSTGRES_DB: system_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - pg_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d system_management"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    container_name: redis-local
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # Container para teste de servidor de email
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface web

  # Container para teste de servidor de arquivo S3
  minio:
    container_name: minio-S3
    image: minio/minio
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Interface web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_test_data:
  minio_data:

networks:
  pg_net:
    driver: bridge