services:
  postgres:
    image: postgres:15.14-alpine3.21
    container_name: system_management_postgres_test
    restart: unless-stopped
    shm_size: 64mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-123
      POSTGRES_DB: system_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - pg_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d system_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:

networks:
  pg_net:
    driver: bridge