spring.sql.init.data-locations=classpath:schema/data_prod_dev.sql

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL_TEST}
spring.datasource.username=${DATABASE_USERNAME_TEST}
spring.datasource.password=${DATABASE_PASSWORD_TEST}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST}
spring.cache.type=redis

spring.mail.host=${EMAIL_HOST_TEST}
spring.mail.port=${EMAIL_PORT_TEST}
spring.mail.username=${EMAIL_USERNAME_TEST}
spring.mail.password=${EMAIL_PASSWORD_TEST}
spring.mail.properties.mail.smtp.auth=${EMAIL_SMTP_AUTH_TEST}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_SMTP_STARTTLS_TEST}

web.site.url.front-end=${FRONT_END_URL}
api.v1.url.back-end=${BACK_END_URL}

api.v1.mercado.pago.access-token=${MERCADO_PAGO_ACCESS_TOKEN_TEST}
api.v1.mercado.pago.notification=${MERCADO_PAGO_NOTIFICATION_TEST}
api.v1.mercado.pago.webhook-secret=${MERCADO_PAGO_WEBHOOK_SECRET_TEST}