spring.sql.init.data-locations=classpath:schema/data_test.sql

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=admin
spring.datasource.password=admin
spring.h2.console.enabled=true
spring.h2.console.path=/console-h2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

api.v1.mercado.pago.access-token=TEST-4618289697580653-030821-90ba6f7624171c6d6448a757d5f7a913-3253136173
api.v1.mercado.pago.notification=https://overderisive-klara-punctually.ngrok-free.dev/api/v1/webhooks/mercado-pago
api.v1.mercado.pago.webhook-secret=c055e0bba1e5012a516193cb72c68843bec773ede24ef55837cda9cbbeba490c